name: build-and-test
on:
  # Testing - run for any PRs.
  pull_request:
    branches:
      - main

env:
    "PipelineEnvironment": true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies with retry
        run: |
          retries=5
          base_wait_time=15
          exponent=2

          for i in $(seq 1 $retries); do
            if dotnet restore; then
              break
            fi

            if [ $i -lt $retries ]; then
              wait_time=$(awk "BEGIN {print int($base_wait_time * ($exponent ^ ($i - 1)))}")
              echo "dotnet restore failed, retrying in $wait_time seconds..."
              sleep $wait_time
            else
              echo "dotnet restore failed after $retries retries."
              exit 1
            fi
          done

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test test/Soenneker.Utils.AutoBogus.Tests/Soenneker.Utils.AutoBogus.Tests.csproj --no-restore --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release --output .
